# Generated by Django 6.0.4 on 2026-05-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_movie_image_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Drama', 'Drama')], default='Action', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Tamil', 'Tamil'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu')], default='English', max_length=50),
        ),
    ]
