# Generated by Django 6.0.4 on 2026-05-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_genre_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Rom-Com', 'Rom-Com'), ('Love Story', 'Love Story'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Drama', 'Drama'), ('Thriller', 'Thriller'), ('Adventure', 'Adventure')], default='Action', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Tamil', 'Tamil'), ('Malayalam', 'Malayalam'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu')], default='English', max_length=50),
        ),
    ]
