# Generated by Django 6.0.4 on 2026-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
