# Generated by Django 6.0.4 on 2026-05-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_seat_reserved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
