# Generated by Django 6.0.4 on 2026-05-26 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_processedwebhook_booking_processed_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='movies_book_booked__a7ab7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='movies_book_payment_94dd93_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='movies_book_movie_i_71732a_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='movies_book_theater_f50fb6_idx',
        ),
        migrations.AddField(
            model_name='processedwebhook',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='booking',
            name='processed_at',
        ),
    ]
